apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
- ../../base/app
- ../../base/cache
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: app
configurations:
- kustomizeconfig.yaml
images:
- name: frontend
  newName: gitopsrun/webapp-frontend
  newTag: 05d85d2
