apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
- ../../base/app
- ../../base/cache
vars:
  - name: NAMESPACE
    objref:
      kind: Deployment
      name: app
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.namespace
configurations:
  - kustomizeconfig.yaml
images:
- name: frontend
  newName: gitopsrun/frontend
  newTag: 0.0.1
